### ISSUE TITLE
Auto Kick Modder - Remembered Not functioning

### ISSUE THREAD

**Issue by thedoctorjtd** [DemonKiya/2Take1Script-Revive#11]
**Description of the bug**
Auto Kick Modder functions as intended EXCEPT for the 'Remembered' toggle. A remembered modder will join the session and not be kicked. Log history below. 

**How to replicate**
Have remember modders on with several flags (not sure if which flags affect things)
Have auto kick modder on with remembered selected 
--I have my autokick and remembered flags identical--

Modder meeting criteria of both remembered and automod is detected. They are kicked successfully. 
They rejoin the same session
Remembered flags them and notifies
Remembered marks them as a modder with 2take1 UI showing flag as Remembered
Automod DOES NOT kick them for being remembered

**Expected behavior**
1 - Automod should detect a remembered modder if the respective flag is selected and appropriately kick the modder. 

2 - If possible, remembered should show the original reason in the 2take1 UI instead of just remembered. 
Options: Remembered Karen, Remembered Godmode || Remembered & Karen & Godmode

3 - Optional enhancement
Rework auto kick modder remembered flag to only kick modders that were remembered for items on the auto-kick list. 
Example - I want to remember all modders but I don't want to kick someone that was remembered for godmode. Because they were only remembered for godmode, automod would not kick them. However someone that was remembered for Karen would be kicked as both remembered AND Karen were flagged. 

**Screenshots / Videos / Logs**
If possible, add screenshots or videos of the bug to the report or
post the last bug related error message from `%appdata%\PopstarDevs\2Take1Menu\2Take1Menu.log` or upload the file

Censored log excerpt:
[2022-06-10 17:25:52] [Modder Detection] Player: badperson
Reason: Session Mismatch
[2022-06-10 17:25:52] Player: badperson
Reason: Session Mismatch
Reaction: Kick & Blacklist

--Other Detections--

[2022-06-10 17:26:47] Player: badperson
Reason: Remembered
Modderflag: Session Mismatch

^^This individual was not kicked however was marked in 2take1 UI as modder flag: Remembered^^
![image](https://user-images.githubusercontent.com/76110609/173157318-9ae6d9d2-e980-46d0-a662-d66a367a58a5.png)
![image](https://user-images.githubusercontent.com/76110609/173157358-9b14a76b-6ad5-451f-a338-5f2891718e08.png)

**Additional Info**
Add any other Info about the problem here.

**Comment by DemonKiya** [comment]
I will look into it

**Comment by DemonKiya** [comment]
This issue might be related to something bigger
