### ISSUE TITLE
Keylogger in new version?

### ISSUE THREAD

**Issue by Bluscream** [DemonKiya/2Take1Script-Revive#15]
**Description of the bug**
malwarebytes says Spyware.Keylogger in 2Take1Script.lua

**How to replicate**
1. Install Malwarebytes Premium
2. Try to extract 2Take1Script.lua

**Expected behavior**
Normal extraction

**Screenshots / Videos / Logs**

**Additional Info**

**Comment by DemonKiya** [comment]
Dont use Malwarebytes then lol
My script doesnt contain any malicious code but if you dont trust it anyway, just dont have trusted mode activated or dont use the script at all
