### ISSUE TITLE
Can’t save 2take1 License plate in Vehicles to default or any profile 

### ISSUE THREAD

**Issue by maxd20020** [DemonKiya/2Take1Script-Revive#19]
Can’t save the 2take1 license plate to automatically be on when I load the script, idk if it just a bug on my end but everything else works fine any help would be appreciated ?

**Comment by DemonKiya** [comment]
That feature was never intended to be saved.
I can change it for the next version if i have the time for it

**Comment by DemonKiya** [comment]
changed it for the next version.

**Comment by maxd20020** [comment]
Omg thank you so so much i really appreciate that its one of my fav features ahaha your a proper legend!!! Much respect!!
