### ISSUE TITLE
Random Explode loop

### ISSUE THREAD

**Issue by U-GETTN-HACKED** [DemonKiya/2Take1Script-Revive#27]
**Description of the bug**
Resetting Lua State, Or even Sometimes When Loading Script while in a lobby, Starts to Explode loop a Random Player
**How to replicate**
Reset State or Load Script
**Expected behavior**
Explode Loop on a Random Player, also sometimes starts to Spawn clones(without the Explode loop) (and cars, happened 3 times) infront of the Player with no way of stopping them Spawning except Resetting state again, or unloading script

**Comment by DemonKiya** [comment]
no idea how u guys are getting such errors. No matter how many times i load the script and reset state, everything is working perfectly fine for me
