### ISSUE TITLE
Lua exceptions

### ISSUE THREAD

**Issue by BenceDv** [DemonKiya/2Take1Script-Revive#28]
If I try deleting any type of entity, a Lua exception occurs

Ped manager - Lua Exception [ Failed to resume coroutine ] ? : - 1 : attempt to get length of a number value ( field ' integer index ' ) stack traceback : ? : in function < ?: 70 > 

Vehicle manager - Lua Exception [ Failed to resume coroutine ] ? : - 1 : attempt to get length of a number value ( field ' integer index ' ) stack traceback : ? : in function < ?: 88 >

Object manager - Lua Exception [ Failed to resume coroutine ] ? : - 1 : attempt to get length of a number value ( field ' integer index ' ) stack traceback : ? : in function < ?: 123 >

**Comment by DemonKiya** [comment]
all 3 features are working fine for me and my tester
