### ISSUE TITLE
[BUG] Bodyguards Fuctions

### ISSUE THREAD

**Issue by barbiehunter** [DemonKiya/2Take1Script-Revive#3]
**Describe the bug**
Bodyguards Formation & Distance to Player don't work

**To Reproduce**
1. Go to Bodyguards
2. Select a Formation/Distance
3. Scroll down to Enable Bodyguards & Enable it
4. See the problem(s)

**Expected behavior**
The bodyguards spawn and then just stand around

**Video**
https://user-images.githubusercontent.com/38357837/150656713-dfab6d5c-d592-4b28-aaa0-faf657014953.mp4

**Additional context**
Someone Mentioned it in the Discord server.

**Comment by DemonKiya** [comment]
"Distance" determines the distance the bodyguards are allowed to be away from you before they teleport back, it does not affect the spawn distance.

"Formation" (which is not shown in the video) works totally fine unless the bodyguards are in combat.
