### ISSUE TITLE
Geo-Block China Produces Lua Exception

### ISSUE THREAD

**Issue by LexiTehGallade** [DemonKiya/2Take1Script-Revive#4]
**Description of the bug**
Geo-Block China feature produces Lua Exception on enable. Unsure if still works, but unlikely.

**How to replicate**
1. Go to 'Lobby'
2. Click on 'Communication'
3. Scroll down to 'Geo-Block China'
4. Enable
5. Exception Occurs 

**Expected behavior**
Feature works

**Screenshots / Videos / Logs**
https://i.imgur.com/NofWV93.png

**Additional Info**
N/A

**Comment by DemonKiya** [comment]
Fixed for the next version
