### ISSUE TITLE
[BUG] Bounty after Death

### ISSUE THREAD

**Issue by barbiehunter** [DemonKiya/2Take1Script-Revive#5]
**Description of the bug**
If you activate "Reapply Bounty After Death" on a person and the person dies you only get a lua error.

**How to replicate**
1. Go to 'Go to a player'
2. Click on 'Reapply Bounty After the Death'
3. See error

**Screenshots / Videos / Logs**
![SLX2D7](https://user-images.githubusercontent.com/38357837/152032205-43398258-41e6-4879-b03b-4697c8173dd3.png)

```
[2022-02-01 19:50:00] [Error] [Failed to resume coroutine] ...rDevs\2Take1Menu\scripts\2Take1Script/Data/Functions.lua:173: bad argument #-1 to 'trigger_script_event' (number expected, got table)
stack traceback:
	[C]: in field 'trigger_script_event'
	...rDevs\2Take1Menu\scripts\2Take1Script/Data/Functions.lua:173: in field 'set_bounty'
	...Roaming\PopstarDevs\2Take1Menu\scripts\/2Take1Script.lua:8692: in function <...Roaming\PopstarDevs\2Take1Menu\scripts\/2Take1Script.lua:8683>
```

**Comment by DemonKiya** [comment]
fixed for the next version
