### ISSUE TITLE
Repeating Error Message

### ISSUE THREAD

**Issue by ABO896** [DemonKiya/2Take1Script-Revive#7]
Constant Error Message From Script

**How to replicate**
Execute Script and wait

**Expected behavior**
Not sure except the warning message

**Screenshots / Videos / Logs**
[Error] [Failed to resume coroutine] ...\Roaming\PopstarDevs\2Take1Menu\scripts\2Take1Script.lua:5468: attempt to index a number value (local 'player')
stack traceback:
	...\Roaming\PopstarDevs\2Take1Menu\scripts\2Take1Script.lua:5468: in function <...\Roaming\PopstarDevs\2Take1Menu\scripts\2Take1Script.lua:5464>

This every minute or so...

**Additional Info**
Using latest script version

**Comment by DemonKiya** [comment]
yea no the replication steps are wrong, it requires to have "notify typing players" enabled
i already know about it and fixed it for the next release
